"""Add turn_order and notes fields to Game model

Revision ID: b93ef2038be0
Revises: f1837047c988
Create Date: 2025-01-01 18:29:28.259976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b93ef2038be0'
down_revision = 'f1837047c988'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('turn_order', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_column('notes')
        batch_op.drop_column('turn_order')

    # ### end Alembic commands ###
