"""Create game table

Revision ID: f1837047c988
Revises: c7f31d60e36e
Create Date: 2025-01-01 09:10:44.683774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1837047c988'
down_revision = 'c7f31d60e36e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
